### ISSUE TITLE
logback-spring.xml 파일 에러

### ISSUE THREAD

**Issue by thing-zoo** [team-11-challenge/back-end#48]
처음에 logback-spring.xml을 숨겨주기 위해
github secrets 변수에 추가해주고
github actions 시에 logback-spring.xml 파일이 생성되도록 했다.

그랬더니 서버가 실행 종료되고
도커 로그 파일을 확인해보니 다음과 같은 에러가 발생했다.
```
web    | 2023-08-17T01:29:18.787617496Z Logging system failed to initialize using configuration from 'null'
web    | 2023-08-17T01:29:18.787994973Z java.lang.IllegalStateException: Could not initialize Logback logging from classpath:logback-spring.xml
web    | 2023-08-17T01:29:18.788545293Z 	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:245)
web    | 2023-08-17T01:29:18.788684502Z 	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:80)
web    | 2023-08-17T01:29:18.789067657Z 	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:60)
web    | 2023-08-17T01:29:18.789210867Z 	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:187)
web    | 2023-08-17T01:29:18.789341523Z 	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:332)
web    | 2023-08-17T01:29:18.789479602Z 	at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:298)
web    | 2023-08-17T01:29:18.789660266Z 	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:246)
web    | 2023-08-17T01:29:18.789792186Z 	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:223)
web    | 2023-08-17T01:29:18.789870247Z 	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
web    | 2023-08-17T01:29:18.789973654Z 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
web    | 2023-08-17T01:29:18.790095091Z 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
web    | 2023-08-17T01:29:18.790191637Z 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
web    | 2023-08-17T01:29:18.790312186Z 	at org.springframework.boot.context.event.EventPublishingRunListener.multicastInitialEvent(EventPublishingRunListener.java:136)
web    | 2023-08-17T01:29:18.790423420Z 	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:81)
web    | 2023-08-17T01:29:18.790537132Z 	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:64)
web    | 2023-08-17T01:29:18.790669555Z 	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
web    | 2023-08-17T01:29:18.790800347Z 	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
web    | 2023-08-17T01:29:18.790911070Z 	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
web    | 2023-08-17T01:29:18.790989566Z 	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:63)
web    | 2023-08-17T01:29:18.791111344Z 	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:356)
web    | 2023-08-17T01:29:18.791226837Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
web    | 2023-08-17T01:29:18.791350693Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
web    | 2023-08-17T01:29:18.791502731Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
web    | 2023-08-17T01:29:18.791666823Z 	at com.example.courseregistratioonbackend.CourseRegistratioonBackendApplication.main(CourseRegistratioonBackendApplication.java:10)
web    | 2023-08-17T01:29:18.791791290Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
web    | 2023-08-17T01:29:18.791940155Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
web    | 2023-08-17T01:29:18.792021511Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
web    | 2023-08-17T01:29:18.792140614Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
web    | 2023-08-17T01:29:18.792241063Z 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
web    | 2023-08-17T01:29:18.792395693Z 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
web    | 2023-08-17T01:29:18.792563235Z 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
web    | 2023-08-17T01:29:18.792754321Z 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
web    | 2023-08-17T01:29:18.793430177Z Caused by: ch.qos.logback.core.joran.spi.JoranException: Problem parsing XML document. See previously reported errors.
web    | 2023-08-17T01:29:18.793565406Z 	at ch.qos.logback.core.joran.event.SaxEventRecorder.recordEvents(SaxEventRecorder.java:70)
web    | 2023-08-17T01:29:18.793676713Z 	at ch.qos.logback.core.joran.GenericXMLConfigurator.populateSaxEventRecorder(GenericXMLConfigurator.java:188)
web    | 2023-08-17T01:29:18.793786303Z 	at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:162)
web    | 2023-08-17T01:29:18.794176828Z 	at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:126)
web    | 2023-08-17T01:29:18.794309038Z 	at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:69)
web    | 2023-08-17T01:29:18.794419103Z 	at org.springframework.boot.logging.logback.LogbackLoggingSystem.configureByResourceUrl(LogbackLoggingSystem.java:272)
web    | 2023-08-17T01:29:18.794633938Z 	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:242)
web    | 2023-08-17T01:29:18.795072385Z 	... 31 more
web    | 2023-08-17T01:29:18.795357090Z Caused by: org.xml.sax.SAXParseException; systemId: jar:file:/app.jar!/BOOT-INF/classes!/logback-spring.xml; lineNumber: 1; columnNumber: 15; The value following "version" in the XML declaration must be a quoted string.
web    | 2023-08-17T01:29:18.795478238Z 	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1251)
web    | 2023-08-17T01:29:18.795632473Z 	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
web    | 2023-08-17T01:29:18.796179277Z 	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:326)
web    | 2023-08-17T01:29:18.796303775Z 	at ch.qos.logback.core.joran.event.SaxEventRecorder.recordEvents(SaxEventRecorder.java:64)
web    | 2023-08-17T01:29:18.796384889Z 	... 37 more
web exited with code 1
```

**Comment by thing-zoo** [comment]
아무래도 logback-spring.xml 파일이 생성되지 않는 것 같아
logback-spring.xml을 직접 넣어주니 해결되었다..!ㅠ
