### ISSUE TITLE
redis sorted set의 rank()가 null을 반환하는 경우

### ISSUE THREAD

**Issue by thing-zoo** [team-11-challenge/back-end#84]
convertAndSend에서 메세지를 보내려는 데 payload가 null이라 발생한 에러다.
```Java
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "payload" is null
	at org.springframework.messaging.converter.AbstractMessageConverter.canConvertTo(AbstractMessageConverter.java:233)
	at org.springframework.messaging.converter.AbstractMessageConverter.toMessage(AbstractMessageConverter.java:197)
	at org.springframework.messaging.converter.CompositeMessageConverter.toMessage(CompositeMessageConverter.java:96)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.doConvert(AbstractMessageSendingTemplate.java:177)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.convertAndSend(AbstractMessageSendingTemplate.java:150)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.convertAndSend(AbstractMessageSendingTemplate.java:129)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.convertAndSend(AbstractMessageSendingTemplate.java:122)
	at com.example.courseregistratioonbackend.domain.registration.service.QueueService.getOrder(QueueService.java:75)
	at com.example.courseregistratioonbackend.domain.registration.event.EventScheduler.getOrder(EventScheduler.java:18)
	at jdk.internal.reflect.GeneratedMethodAccessor67.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by thing-zoo** [comment]
코드를 살펴보니 payload인 rank 값이 null 이 반환되었다.
아마 반복문을 도는 동안, 다른 스레드에 의해 해당 요청이 set에서 삭제될 수 있기 때문에 발생한 것 같다.
```Java
// QueueService.java
for (String member : queue) {
    Long rank = redisTemplate.opsForZSet().rank(event.toString(), member);
    RegistrationRequestDto requestDto = objectMapper.readValue(member, RegistrationRequestDto.class);
    log.info("'{}'님의 현재 대기열은 {}명 남았습니다.", requestDto, rank);
    simpMessageSendingOperations.convertAndSend("/sub/order/" + requestDto.getStudentNM(), rank);
}
```
